// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJLzibwqmZ4xbfw31P2QcKsmC3rEQB00I',
    appId: '1:751123895130:web:fdbbe25a76389672601963',
    messagingSenderId: '751123895130',
    projectId: 'isaac-wiki-8cef9',
    authDomain: 'isaac-wiki-8cef9.firebaseapp.com',
    storageBucket: 'isaac-wiki-8cef9.firebasestorage.app',
    measurementId: 'G-J5HNLPZ046',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmpnkH_6Oq0YSPNXuGRLH9lAUUAflaUDw',
    appId: '1:751123895130:android:e9eedd6715887010601963',
    messagingSenderId: '751123895130',
    projectId: 'isaac-wiki-8cef9',
    storageBucket: 'isaac-wiki-8cef9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnLYFtP1XLyPE6EGT5a4DTJ-8hhE8wox8',
    appId: '1:751123895130:ios:0af78b2577500cde601963',
    messagingSenderId: '751123895130',
    projectId: 'isaac-wiki-8cef9',
    storageBucket: 'isaac-wiki-8cef9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnLYFtP1XLyPE6EGT5a4DTJ-8hhE8wox8',
    appId: '1:751123895130:ios:0af78b2577500cde601963',
    messagingSenderId: '751123895130',
    projectId: 'isaac-wiki-8cef9',
    storageBucket: 'isaac-wiki-8cef9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJLzibwqmZ4xbfw31P2QcKsmC3rEQB00I',
    appId: '1:751123895130:web:49a2287a9b1c240c601963',
    messagingSenderId: '751123895130',
    projectId: 'isaac-wiki-8cef9',
    authDomain: 'isaac-wiki-8cef9.firebaseapp.com',
    storageBucket: 'isaac-wiki-8cef9.firebasestorage.app',
    measurementId: 'G-QLSL5R0RVS',
  );
}
